import { SlideTheme } from '@/types';

export const SLIDE_THEMES: SlideTheme[] = [
  {
    id: 'academic-navy',
    name: 'Klassik Akademik',
    category: 'Academic',
    bgGradient: 'bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#172554]',
    previewBg: 'from-slate-900 to-blue-950',
    textColor: 'text-white',
    subtitleColor: 'text-blue-200',
    accentColor: 'text-amber-400',
    cardBg: 'bg-white/10 backdrop-blur-md border border-white/15',
    fontFamily: 'font-serif',
    pptxBg: '0F172A',
    pptxTextColor: 'FFFFFF',
    pptxAccentColor: 'F59E0B',
    pptxCardBg: '1E293B',
  },
  {
    id: 'modern-dark',
    name: 'Zamonaviy Texnologiya',
    category: 'Dark',
    bgGradient: 'bg-gradient-to-br from-[#050505] via-[#091524] to-[#042f2e]',
    previewBg: 'from-neutral-950 to-teal-950',
    textColor: 'text-slate-100',
    subtitleColor: 'text-teal-300',
    accentColor: 'text-cyan-400',
    cardBg: 'bg-slate-900/80 backdrop-blur-md border border-cyan-500/20 shadow-cyan-900/20 shadow-lg',
    fontFamily: 'font-sans',
    pptxBg: '050B14',
    pptxTextColor: 'F1F5F9',
    pptxAccentColor: '06B6D4',
    pptxCardBg: '0F172A',
  },
  {
    id: 'ivory-minimal',
    name: 'Nafis Fil Suyagi',
    category: 'Minimal',
    bgGradient: 'bg-gradient-to-br from-[#fefcf8] via-[#f7f4ed] to-[#ede7dc]',
    previewBg: 'from-amber-50 to-orange-100',
    textColor: 'text-stone-900',
    subtitleColor: 'text-stone-600',
    accentColor: 'text-amber-700',
    cardBg: 'bg-white/80 backdrop-blur-md border border-stone-200 shadow-sm',
    fontFamily: 'font-serif',
    pptxBg: 'FEFCF8',
    pptxTextColor: '1C1917',
    pptxAccentColor: 'B45309',
    pptxCardBg: 'F5F0E6',
  },
  {
    id: 'emerald-science',
    name: 'Zumrad Ilm-Fan',
    category: 'Academic',
    bgGradient: 'bg-gradient-to-br from-[#022c22] via-[#064e3b] to-[#043d30]',
    previewBg: 'from-emerald-950 to-teal-900',
    textColor: 'text-emerald-50',
    subtitleColor: 'text-emerald-200',
    accentColor: 'text-emerald-400',
    cardBg: 'bg-white/10 backdrop-blur-md border border-emerald-400/20',
    fontFamily: 'font-sans',
    pptxBg: '022C22',
    pptxTextColor: 'ECFDF5',
    pptxAccentColor: '34D399',
    pptxCardBg: '064E3B',
  },
  {
    id: 'creative-violet',
    name: 'Ijodiy Gradiyent',
    category: 'Creative',
    bgGradient: 'bg-gradient-to-br from-[#311042] via-[#4c1d95] to-[#701a75]',
    previewBg: 'from-purple-900 to-fuchsia-900',
    textColor: 'text-white',
    subtitleColor: 'text-purple-200',
    accentColor: 'text-pink-400',
    cardBg: 'bg-white/15 backdrop-blur-md border border-white/20 shadow-xl',
    fontFamily: 'font-sans',
    pptxBg: '311042',
    pptxTextColor: 'FFFFFF',
    pptxAccentColor: 'F472B6',
    pptxCardBg: '4C1D95',
  },
  {
    id: 'clean-white',
    name: 'Oq & Moviy Minimal',
    category: 'Minimal',
    bgGradient: 'bg-gradient-to-br from-[#ffffff] via-[#f0f7ff] to-[#e0effe]',
    previewBg: 'from-white to-blue-100',
    textColor: 'text-slate-900',
    subtitleColor: 'text-slate-600',
    accentColor: 'text-blue-600',
    cardBg: 'bg-white/95 backdrop-blur-md border border-blue-100 shadow-md',
    fontFamily: 'font-sans',
    pptxBg: 'FFFFFF',
    pptxTextColor: '0F172A',
    pptxAccentColor: '2563EB',
    pptxCardBg: 'F0F7FF',
  },
  {
    id: 'sunset-energy',
    name: 'Quyosh Spektri',
    category: 'Creative',
    bgGradient: 'bg-gradient-to-br from-[#1c1917] via-[#431407] to-[#7c2d12]',
    previewBg: 'from-stone-900 to-orange-950',
    textColor: 'text-amber-50',
    subtitleColor: 'text-orange-200',
    accentColor: 'text-orange-400',
    cardBg: 'bg-black/30 backdrop-blur-md border border-orange-500/20',
    fontFamily: 'font-sans',
    pptxBg: '1C1917',
    pptxTextColor: 'FFFBEB',
    pptxAccentColor: 'FB923C',
    pptxCardBg: '431407',
  },
  {
    id: 'pastel-modern',
    name: 'Pastel Studio',
    category: 'Modern',
    bgGradient: 'bg-gradient-to-br from-[#f8fafc] via-[#ede9fe] to-[#e0e7ff]',
    previewBg: 'from-violet-100 to-indigo-100',
    textColor: 'text-indigo-950',
    subtitleColor: 'text-indigo-700',
    accentColor: 'text-violet-600',
    cardBg: 'bg-white/80 backdrop-blur-md border border-indigo-200/60 shadow-sm',
    fontFamily: 'font-sans',
    pptxBg: 'F8FAFC',
    pptxTextColor: '1E1B4B',
    pptxAccentColor: '7C3AED',
    pptxCardBg: 'EDE9FE',
  }
];

export const DEFAULT_THEME_ID = 'academic-navy';

export function getTheme(themeId?: string): SlideTheme {
  const found = SLIDE_THEMES.find(t => t.id === themeId);
  return found || SLIDE_THEMES[0];
}
